global:
  httpTimeout: 500ms
  rpcTimeout: 5s
  rpcRetryTimes: 5
  showError: false

dingofs:
  mdsAddr: 127.0.0.1:6700,127.0.0.1:6701,127.0.0.1:6702  # __DINGOADM_TEMPLATE__ ${cluster_mds_addr} __DINGOADM_TEMPLATE__
  storagetype: s3  # s3 or rados
  s3:
    ak: ak
    sk: sk
    endpoint: http://localhost:9000
    bucketname: bucketname
    blocksize: 4 mib
    chunksize: 64 mib
  rados:
    username: client.dingofs-rgw
    key: AQANAExo/ihMLBAAPL8AXgqfxwdraw8uoWyJig==
    mon: 10.220.69.5:3300,10.220.69.6:3300,10.220.69.8:3300
    poolname: rados.dingofs.data
    blocksize: 4 mib
    chunksize: 64 mib
