name: Release Artifact

on:
  push:
    branches: [ "**" ]
    tags:
      - '*'

jobs:
  build:
    if: ${{ !startsWith(github.ref, 'refs/heads/gh-readonly-queue/') }}
    runs-on: ubuntu-latest
    container: dingodatabase/dingo-eureka:rocky9-fs

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Record event type
        run: |
          branchName=$(echo "${{ github.ref_name }}")
          echo "branch name is: $branchName"
          echo "BRANCH_NAME=$branchName" >> $GITHUB_ENV

          echo "hello dingo eureka" > event.txt
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "EVENT_TYPE=PR" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" == "push" ]; then
            if [[ "${{ github.ref }}" == refs/tags/* ]]; then
              echo "EVENT_TYPE=TAG" >> $GITHUB_ENV
              tagInfo=echo "${{ github.ref }}" | sed 's/refs\/tags\///'
              echo "TAG_NAME=$tagInfo" >> $GITHUB_ENV
            else
              echo "EVENT_TYPE=PUSH" >> $GITHUB_ENV
              echo "TAG_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
            fi
          fi
      
      - name: Set Safe Dir
        run: git config --global --add safe.directory $PWD

      - name: Sync submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive
  
      - name: Build binary
        run: |
          make build

      - name: Release
        uses: softprops/action-gh-release@v2
        if: ${{ github.event_name == 'push'}}
        with:
          files: |
            sbin/dingo
            sbin/daemon
          name: ${{ env.BRANCH_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          token: ${{ secrets.GH_TOKEN }}